### ISSUE TITLE
Slow on iPad Air 2

### ISSUE THREAD

**Issue by saturngod** [Adonit/JotTouchSDK#27]
I am using Jotscript. I tested the example code on iPad Air 2 , jottouchsdk response is too slow and late 1 or 2 seconds the touch event.

**Comment by jarbogast** [comment]
We just released v2.6.5 which addresses many issues with iPad Air 2. Have things improved?

**Comment by saturngod** [comment]
not so much different. Still useless for iPad Air 2. But Jot Script with NoteShelf app is better than the other apps that using Jot Script SDK (example : GoodNotes).

**Comment by jarbogast** [comment]
Sorry to hear that.

Although we just released v2.6.5 of our SDK, it takes time for each individual application to incorporate each release of ours. Then that new application has to be submitted and approved by Apple before it reaches you. I would suggest checking-in with NoteShelf/GoodNotes/etc and asking what version of the SDK they are using and what their plans are for future releases.

We're working hard on this end to ensure that developers at least know about this release of the SDK and we're encouraging them to get those updates out to you as soon as they can.

**Comment by jarbogast** [comment]
You can always contact customer support at help@adonit.net. They may have more information on the application you're trying to use as well as other useful information to help improve your experience with Jot Script.
