### ISSUE TITLE
How to implement multiple CanvasViews inside the CustomScrollView 

### ISSUE THREAD

**Issue by andrespch** [Adonit/JotTouchSDK#28]
I'm trying to implement a multiple page functionality for an app that is using the example project as guide,  the problem I'm facing is that the lines are not being rendered starting from the second canvas view that is added, it works good only for the first canvas view that is created, I checked for touch events and they are being triggered as expected, is just the drawing that is not happening, can you please give me an idea what might be causing this problem? 

Thank you.

**Comment by jarbogast** [comment]
Are you registering each CanvasView that you're creating with the JotStylusManager by calling registerView:? Each view that's dedicated to drawing needs to be registered with the stylus manager before it will start receiving the JotTouchBegan/Moved/Ended/Cancelled events for drawing.

**Comment by andrespch** [comment]
Hey thanks for answering, yes I am, in fact as I said I'm sure the events are being fired, and the the drawing code is being executed, I event checked the vertex data  and seems normal, the lines just won't appear on the view after they are "rendered". I think its an OpenGL configuration issue. Still trying to find out what it is.

**Comment by andrespch** [comment]
another quick question, is there an specific reason why you guys are using OpenGL1 ? is there anything to consider when wanting to use OpenGL2 or 3 with the jottouchSDK?

**Comment by jarbogast** [comment]
The honest answer is that we just haven't taken the time to update our example app to use the latest and greatest OpenGL technology and/or support different kinds of OpenGL configurations.

The example app is simply meant to demonstrate how to connect the JotTouchSDK to a typical drawing application. The actual drawing engine you use or create is totally up to you!

**Comment by andrespch** [comment]
Okay, thanks for taking the time to answer my questions!
